[package]
name = "game_jam_test"
version = "0.1.0"
authors = ["Brandon <branmh@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.3"